import React, { createContext, useContext, useState, useEffect } from 'react';

// Dictionaries mapping Arabic (Default) to English
export const dictionaries = {
  ar: {},
  en: {
    // Navigation & Layouts
    "النخبة": "Elite",
    "الرئيسية": "Home",
    "عن المنصة": "About Us",
    "تواصل معنا": "Contact Us",
    "تسجيل الدخول": "Login",
    "إنشاء حساب": "Sign Up",
    "لوحة التحكم": "Dashboard",
    "تسجيل الخروج": "Logout",
    "النخبة — لوحة التحكم": "Elite — Dashboard",
    "مدير النظام": "Administrator",
    "ابحث في المنصة...": "Search platform...",
    "الإشعارات": "Notifications",
    "تحديد الكل كمقروء": "Mark all as read",
    "عرض كل الإشعارات القديمة": "View all older notifications",
    "طالب جامعي": "University Student",
    "موادي": "My Subjects",
    "اختباراتي": "My Quizzes",
    "التحديات": "Challenges",
    "مواردي": "My Resources",
    "إعدادات الحساب": "Account Settings",
    "تفعيل الاشتراك": "Activate Subscription",
    "لوحة الإحصائيات": "Analytics Dashboard",
    "إدارة المستخدمين": "User Management",
    "إدارة التخصصات": "Majors Management",
    "إدارة المواد": "Subjects Management",
    "إدارة الموارد": "Resources Management",
    "إدارة البلاغات": "Reports Management",
    "إدارة الاقتراحات": "Suggestions Management",
    "الاشتراكات": "Subscriptions",
    "بطاقات الاشتراك": "Subscription Cards",
    "تم تصديرها": "Exported",
    "السعر (ر.ي)": "Price (YER)",
    "جميع الخطط": "All Plans",
    "إعدادات النظام": "System Settings",

    // Public Landing Pages
    "مستقبلك يبدأ من هنا": "Your future begins here",
    "اختر تخصصك": "Choose Your",
    "الجامعي ": "University Major",
    "بثقة": "Confidently",
    "منصة النخبة تساعدك على اكتشاف تخصصك المناسب بناءً على ميولك وقدراتك، وترافقك للنجاح في دراستك الجامعية عبر أدوات ذكية وموارد تعليمية متميزة.": "The Elite platform helps you discover the right major based on your interests and abilities, and accompanies you to success in your academics through smart tools and premium educational resources.",
    "ابدأ اختبار الميول": "Start Interest Test",
    "استكشف التخصصات": "Explore Majors",
    "انضم لأكثر من 2000 طالب وطالبة": "Join over 2000 students",
    "طلاب يدرسون معًا": "Students studying together",
    "تم تحديد التخصص": "Major Identified",
    "تقنية معلومات  — 98% توافق": "Computer Science — 98% Match",
    "ماذا تقدم لك منصة النخبة؟": "What does the Elite Platform offer you?",
    "نقدم لك مجموعة متكاملة من الأدوات لمساعدتك في كل خطوة من رحلتك الأكاديمية": "We offer a complete suite of tools to help you every step of your academic journey",
    "اكتشف تخصصك المناسب": "Discover Your Perfect Major",
    "اختبار ميول علمي يساعدك في اختيار المجال الدراسي الأنسب لشخصيتك وقدراتك.": "A scientific interest test that helps you choose the field of study best suited to your personality and abilities.",
    "اختبر نفسك في موادك": "Test Yourself in Subjects",
    "ارفع ملفات المادة وسيقوم الذكاء الاصطناعي بتوليد اختبارات تفاعلية لتعميق فهمك.": "Upload course files and AI will generate interactive quizzes to deepen your understanding.",
    "شارك المعرفة": "Share Knowledge",
    "مجتمع طلابي متكامل — ارفع ملخصاتك وشاركها مع زملائك، واستفد من مواردهم.": "An integrated student community — upload and share your summaries with peers, and benefit from theirs.",
    "المنصة تخدم الجميع": "The Platform Serves Everyone",
    "سواء كنت تختار تخصصك أو تحسّن مستواك — النخبة معك في كل خطوة": "Whether you are choosing your major or improving your grades — Elite is with you every step",
    "طالب ما قبل الجامعة": "Pre-University Student",
    "اكتشف تخصصك المثالي عبر اختبار الاهتمامات الذكي واطلع على التخصصات المناسبة لك.": "Discover your ideal major via the smart interest test and view suitable specializations.",
    "حسّن مستواك الأكاديمي عبر اختبارات AI وموارد دراسية تشاركية مع زملائك.": "Improve your academic level via AI quizzes and shared study resources with your peers.",
    "دخول لوحة التحكم": "Enter Dashboard",
    "مساهم VIP": "VIP Contributor",
    "انشر ملخصاتك ومواردك مباشرةً وابنِ سمعتك الأكاديمية في مجتمع النخبة.": "Publish your summaries directly and build your academic reputation in the Elite community.",
    "انضم الآن": "Join Now",
    "منصة النخبة الأكاديمية": "Elite Academic Platform",
    "ابدأ رحلتك الأكاديمية اليوم": "Start Your Academic Journey Today",
    "لا تضيع المزيد من الوقت في الحيرة. انضم إلى منصة النخبة الآن واكتشف المسار الذي سيقودك إلى النجاح والتميز.": "Don't waste more time in confusion. Join the Elite platform now and discover the path that will lead you to success and excellence.",

    // Auth & Forms
    "أهلًا بعودتك إلى النخبة": "Welcome back to Elite",
    "تسجيل الدخول": "Login",
    "حسابات تجريبية — كلمة المرور: 123456": "Demo Accounts — Password: 123456",
    "البريد الإلكتروني": "Email Address",
    "أدخل بريدك الإلكتروني": "Enter your email address",
    "كلمة المرور": "Password",
    "أدخل كلمة المرور": "Enter your password",
    "البريد الإلكتروني أو كلمة المرور غير صحيحة": "Incorrect email or password",
    "تذكرني": "Remember me",
    "نسيت كلمة المرور؟": "Forgot your password?",
    "جاري الدخول...": "Logging in...",
    "← تسجيل الدخول": "Login",
    "ليس لديك حساب؟ ": "Don't have an account? ",
    "إنشاء حساب": "Create an account",
    "إنشاء حساب جديد": "Create New Account",
    "انضم إلى مجتمع النخبة الأكاديمي": "Join the Elite academic community",
    "الاسم الأول": "First Name",
    "اسم الأب": "Father's Name",
    "اسم الجد": "Grandfather's Name",
    "الاسم الأخير": "Last Name",
    "رقم الهاتف": "Phone Number",
    "تأكيد كلمة المرور": "Confirm Password",
    "الصورة الشخصية (اختياري)": "Profile Picture (Optional)",
    "انقر لرفع صورة — JPG أو PNG بحد أقصى 2MB": "Click to upload an image — JPG or PNG max 2MB",
    "هل أنت طالب جامعي حالياً؟": "Are you currently a university student?",
    "فعّل هذا الخيار لتتمكن من الوصول إلى لوحة تحكم الطالب الجامعي": "Enable this to access the university student dashboard",
    "معلومات الطالب الجامعي": "University Student Information",
    "الجامعة": "University",
    "اسم الجامعة": "University Name",
    "التخصص": "Major",
    "تخصصك الجامعي": "Your University Major",
    "الرقم الأكاديمي": "Academic ID",
    "المستوى الدراسي": "Academic Level",
    "المستوى الأول": "Level 1",
    "الثاني": "Level 2",
    "الثالث": "Level 3",
    "الرابع": "Level 4",
    "الخامس": "Level 5",
    "السادس": "Level 6",
    "السابع": "Level 7",
    "الثامن": "Level 8",
    "أدخل كود البطاقة — صيغة: ": "Enter Card Code — Format: ",
    "الكود صحيح — سيتم تفعيل الاشتراك عند إنشاء الحساب": "Code is valid — Subscription will be activated upon account creation",
    "الكود غير صحيح أو مستخدم مسبقاً": "Code is invalid or already used",
    "انقر خارج الحقل للتحقق من الكود": "Click outside the field to verify code",
    "إنشاء الحساب وتفعيل الاشتراك": "Create Account & Activate Subscription",
    "← إنشاء الحساب": "Create Account",
    "لديك حساب بالفعل؟ ": "Already have an account? ",
    "مستخدم جديد": "New User",
    "مشرف محتوى": "Content Moderator",
    "أدمن": "Admin",

    // Dashboard Base & Subjects
    "مرحبًا، محمد": "Welcome, Mohammed",
    "هذه لوحة تحكمك الأكاديمية": "This is your academic dashboard",
    "عدد الاختبارات": "Number of Quizzes",
    "متوسط النتائج": "Average Score",
    "عدد الموارد المضافة": "Added Resources",
    "نقاط المساهمة": "Contribution Points",
    "آخر الاختبارات": "Recent Quizzes",
    "عرض الكل": "View All",
    "← إجراء اختبار جديد": "← Start New Quiz",
    "إجراءات سريعة": "Quick Actions",
    "توليد اختبار AI": "Generate AI Quiz",
    "إدارة موادي": "Manage My Subjects",
    "رفع مورد جديد": "Upload New Resource",
    "الإشعارات": "Notifications",
    "مواد هذا الفصل": "This Semester Subjects",
    "إدارة المواد": "Manage Subjects",
    "موادي": "My Subjects",
    "اختر مواد فصلك الدراسي (الحد الأدنى 4 مواد - الأقصى 12 مادة)": "Select your semester subjects (Min 4 - Max 12)",
    "لا يمكنك اختيار أكثر من 12 مادة بحد أقصى": "You cannot select more than 12 subjects",
    "يجب اختيار 4 مواد على الأقل": "You must select at least 4 subjects",
    "تصفح المادة ←": "Browse Subject ←",
    "تم حفظ المواد": "Subjects Saved",
    "← حفظ المواد المختارة": "← Save Selected Subjects",
    "تم اختيار ": "Selected ",
    " من 12 مادة كحد أقصى": " of 12 subjects max",
    "يتطلب اشتراكًا": "Requires Subscription",

    // Subject Names
    "رياضيات متقدمة": "Advanced Math",
    "فيزياء 2": "Physics 2",
    "خوارزميات": "Algorithms",
    "قواعد البيانات المتقدمة": "Advanced Databases",
    "ذكاء اصطناعي": "Artificial Intelligence",
    "هندسة البرمجيات": "Software Engineering",
    "تطبيقات الويب": "Web Applications",
    "أمن المعلومات": "Information Security",
    "الشبكات": "Networks",
    "الحوسبة السحابية": "Cloud Computing",
    "التفاعل بين الإنسان والحاسوب": "Human-Computer Interaction",
    "نظم التشغيل": "Operating Systems",
    "هياكل بيانات متقدمة": "Advanced Data Structures",

    // Subject Details
    "الملخصات (القسم الأكاديمي)": "Summaries (Academic Section)",
    "الدورات والشروحات": "Courses & Explanations",
    "أحدث الملخصات": "Latest Summaries",
    "طلب ملخص": "Request Summary",
    "+ رفع ملخص جديد": "+ Upload New Summary",
    "تحميل الملف ↓": "Download File ↓",
    "لا توجد ملخصات بعد": "No summaries yet",
    "كن أول من يرفع ملخصاً لهذه المادة!": "Be the first to upload a summary for this subject!",
    "شروحات مرئية ودورات مكثفة": "Visual Explanations & Intensive Courses",
    "+ إضافة دورة": "+ Add Course",
    " إعجاب": " Likes",
    "فتح الرابط ↗": "Open Link ↗",
    "← العودة للمواد": "← Back to Subjects",
    "هذه الصفحة مخصصة لعرض جميع المصادر التعليمية والملخصات والدورات الخاصة بمادة ": "This page displays all educational resources, summaries, and courses for ",
    ". يمكنك الاستفادة من المحتوى الذي يشاركه زملاؤك أو رفع ملخصاتك الخاصة.": ". You can benefit from content shared by peers or upload your own.",

    // Resources & Quizzes
    "مواردي": "My Resources",
    "ملخصاتك ودوراتك الدراسية المشتركة": "Your summaries and shared courses",
    "الملخصات": "Summaries",
    "الدورات": "Courses",
    "مقبول": "Approved",
    "قيد المراجعة": "Pending",
    "مرفوض": "Rejected",
    " نقطة": " Points",
    "تحميل": "Download",
    "طلب ملخص مفقود": "Request Missing Summary",
    "← إضافة دورة جديدة": "← Add New Course",
    "رفع ملخص جديد": "Upload New Summary",
    "المادة الدراسية": "Subject",
    "اختر المادة...": "Select Subject...",
    "عنوان الملخص": "Summary Title",
    "مثال: ملخص الفصل الأول...": "Example: Chapter 1 Summary...",
    "اسم الدكتور (اختياري)": "Doctor Name (Optional)",
    "مثال: د. أحمد محمد": "Example: Dr. Ahmed Mohammed",
    "وصف قصير": "Short Description",
    "اكتب نبذة عن محتوى الملخص...": "Write a brief description of the summary...",
    "ملف الملخص (PDF, PPTX, DOCX)": "Summary File (PDF, PPTX, DOCX)",
    "إخفاء اسمي كمساهم (نشر كـ مجهول)": "Hide my name as contributor (Publish anonymously)",
    "إلغاء": "Cancel",
    "← رفع الملخص": "← Upload Summary",
    "سيتم إرسال طلبك للطلاب المميزين والمساهمين في هذه المادة.": "Your request will be sent to top students and contributors for this subject.",
    "موضوع الطلب / الجزء المفقود": "Request Subject / Missing Part",
    "مثال: أحتاج لملخص يشرح خوارزميات الترتيب (Sorting Algorithms) للفصل الرابع...": "Example: I need a summary explaining Sorting Algorithms for Chapter 4...",
    "← إرسال الطلب": "← Send Request",
    "اختباراتي": "My Quizzes",
    "جميع اختباراتك السابقة": "All your previous quizzes",
    "اختبار أجريته": "Quiz Taken",
    "متوسط درجاتك": "Your Average Score",
    "إجمالي وقت الدراسة": "Total Study Time",
    " سؤال": " Questions",
    " صحيحة": " Correct",
    "مراجعة ←": "Review ←",

    // Challenges & Settings & Activate
    "نظام التحديات": "Challenges System",
    "تنافس مع زملائك واختبر معلوماتك في الوقت الفعلي": "Compete with peers and test your knowledge in real-time",
    "+ إعداد تحدي جديد": "+ Create New Challenge",
    "التحديات المتاحة الحالية": "Active Challenges",
    "سجل تحدياتي السابقة": "Past Challenges Record",
    "مباشر الآن": "Live Now",
    "المادة: ": "Subject: ",
    "كود الدخول": "Access Code",
    " مشارك": " Participants",
    "المدة: ": "Duration: ",
    "انضمام للتحدي بالرابط ←": "Join Challenge via Link ←",
    "عدد المشاركين: ": "Participants Count: ",
    "المركز": "Rank",
    "النتيجة المئوية": "Percentage Score",
    "عرض التفاصيل": "View Details",
    "إعداد تحدي جديد": "Create New Challenge",
    "عنوان التحدي": "Challenge Title",
    "مثال: التحدي الأسبوعي للبرمجة": "Example: Weekly Programming Challenge",
    "المدة الزمنية": "Time Duration",
    "10 دقائق": "10 Minutes",
    "15 دقيقة": "15 Minutes",
    "30 دقيقة": "30 Minutes",
    "أقصى عدد المشاركين": "Max Participants",
    "توليد رابط وكود دخول عام ومشاركته": "Generate and share public link and access code",
    "توليد التحدي ←": "Generate Challenge ←",
    "تفضيلات الإشعارات": "Notification Preferences",
    "إشعارات قبول/رفض الموارد": "Resource Approval/Rejection Notifications",
    "إعجابات على ملخصاتي": "Likes on my summaries",
    "رسائل من المشرفين": "Messages from supervisors",
    "تذكيرات الاختبارات": "Quiz Reminders",
    "النشرة الأسبوعية": "Weekly Newsletter",
    "إعدادات الحساب": "Account Settings",
    "إدارة معلوماتك الشخصية وإعدادات الحساب": "Manage your personal information and account settings",
    "الملف الشخصي": "Profile",
    "الأمان": "Security",
    "الإشعارات": "Notifications",
    "اقتراحاتي": "My Suggestions",
    "الصورة الشخصية": "Profile Picture",
    "تغيير الصورة": "Change Picture",
    "حذف": "Delete",
    "الاسم الأول": "First Name",
    "اسم الأب": "Father's Name",
    "اسم الجد": "Grandfather's Name",
    "الاسم الأخير": "Last Name",
    "رقم الهاتف": "Phone Number",
    "البريد الإلكتروني": "Email Address",
    "← حفظ التغييرات": "← Save Changes",
    "تغيير كلمة المرور": "Change Password",
    "كلمة المرور الحالية": "Current Password",
    "كلمة المرور الجديدة": "New Password",
    "تأكيد كلمة المرور الجديدة": "Confirm New Password",
    "← تحديث كلمة المرور": "← Update Password",
    "تقديم اقتراح للمنصة": "Submit a suggestion to the platform",
    "نحن نهتم برأيك. أخبرنا عن أي ميزة تود رؤيتها في المنصة، أو أبلغنا بمشكلة واجهتك لتحسين تجربتك الدراسية.": "We care about your opinion. Tell us about any feature you'd like to see, or report a problem to improve your experience.",
    "عنوان الاقتراح": "Suggestion Title",
    "مثال: إضافة فيديوهات شرح لكل مادة": "Example: Add explanation videos for each subject",
    "تفاصيل الاقتراح": "Suggestion Details",
    "اشرح لنا اقتراحك أو المشكلة بالتفصيل...": "Explain your suggestion or the problem in detail...",
    "إرسال الاقتراح ←": "Send Suggestion ←",
    "تفعيل الاشتراك": "Activate Subscription",
    "أدخل كود البطاقة المكون من 16 خانة لتفعيل اشتراكك": "Enter the 16-digit card code to activate your subscription",
    "تم التفعيل بنجاح!": "Activated Successfully!",
    "تم تفعيل اشتراكك بنجاح": "Your subscription has been activated successfully",
    "يمكنك الآن الوصول إلى جميع الميزات المميزة": "You can now access all premium features",
    "← الذهاب للوحة التحكم": "← Go to Dashboard",
    "تفعيل كود آخر": "Activate Another Code",
    "صيغة الكود: ": "Code Format: ",
    "الكود غير صحيح أو مستخدم مسبقاً — تحقق من الكود وأعد المحاولة": "Invalid or already used code — Check the code and try again",
    "الكود: NKBH-": "Code: NKBH-",
    "جاهز للتفعيل — اضغط تفعيل الاشتراك": "Ready to activate — Click Activate Subscription",
    "جاري التحقق...": "Verifying...",
    "لا تملك بطاقة اشتراك؟": "Don't have a subscription card?",
    "تواصل مع الدعم": "Contact Support",
    "خطط الاشتراك المتاحة": "Available Subscription Plans",
    "شهري": "Monthly",
    "49 ر.س": "49 SAR",
    "30 يوم": "30 Days",
    "ربع سنوي": "Quarterly",
    "129 ر.س": "129 SAR",
    "90 يوم": "90 Days",
    "سنوي": "Yearly",
    "399 ر.س": "399 SAR",
    "365 يوم": "365 Days",

    // Quizzes, Results and Ranking
    "توليد اختبار بالذكاء الاصطناعي": "Generate AI Quiz",
    "ارفع ملف مادتك وسيقوم الذكاء الاصطناعي بتوليد اختبار تفاعلي": "Upload your subject file and AI will generate an interactive quiz",
    "اسم المادة": "Subject Name",
    "رفع ملف الدراسة": "Upload Study File",
    "اسحب الملف هنا أو انقر للاختيار": "Drag file here or click to select",
    "PDF أو DOCX — حد أقصى 10MB": "PDF or DOCX — Max 10MB",
    "نوع الأسئلة": "Questions Type",
    "اختيار من متعدد + صح/خطأ": "Multiple Choice + True/False",
    "لغة الاختبار": "Quiz Language",
    "حسب محتوى الملف": "Based on file content",
    "عربي": "Arabic",
    "انجليزي": "English",
    "عدد الأسئلة": "Number of Questions",
    "20 سؤال": "20 Questions",
    "توليد الاختبار": "Generate Quiz",
    "جاري التوليد...": "Generating...",
    "وقت الاختبار": "Quiz Time",
    "20 دقيقة": "20 Minutes",
    "40 دقيقة": "40 Minutes",
    "60 دقيقة": "60 Minutes",
    "10 أسئلة": "10 Questions",
    "30 سؤال": "30 Questions",
    "40 سؤال (حد أقصى)": "40 Questions (Max)",
    "50% اختيار من متعدد + 50% صح/خطأ": "50% MCQ + 50% T/F",
    "درجة الصعوبة": "Difficulty Level",
    "بسيط": "Easy",
    "متوسط": "Medium",
    "صعب": "Hard",
    "حجم الملف": "File Size",
    "تفاصيل": "Details",
    "مستوى الطالب": "Student Level",
    "اسم الدكتور المقرر": "Course Doctor",
    "إبلاغ عن المورد": "Report Resource",
    "سبب الإبلاغ": "Reason for Reporting",
    "محتوى غير لائق": "Inappropriate Content",
    "معلومات غير صحيحة": "Incorrect Information",
    "مورد مكرر": "Duplicate Resource",
    "أخرى": "Other",
    "اكتب السبب هنا...": "Write the reason here...",
    "مجهول": "Anonymous",
    "تحميل": "Download",
    "موادي الدراسية": "My Studied Subjects",
    "المواد التي قمت بدراستها مسبقاً": "Subjects you have previously studied",
    "المواد التي قمت بدراستها مسبقاً مقسمة حسب الفصول الدراسية": "Previously studied subjects, grouped by semester",
    "تعديل مواد الترم الحالي": "Edit Current Semester Subjects",
    "مواد الترم الحالي": "Current Semester Subjects",
    "مستوى": "Level",
    "ترم": "Semester",
    "ترم أول": "First Semester",
    "ترم ثاني": "Second Semester",
    "مستوى أول": "Level 1",
    "مستوى ثاني": "Level 2",
    "مستوى ثالث": "Level 3",
    "مستوى رابع": "Level 4",
    "اختيار مواد الترم الحالي": "Select Current Semester Subjects",
    "اختر مواد فصلك الدراسي": "Select your semester subjects",
    "إعادة الاختبار": "Re-take Quiz",
    "اختبار من ملف سابق": "Quiz from previous file",
    "تغيير الملف": "Change File",
    "آخر التنبيهات والإشعارات": "Latest Alerts and Notifications",
    "انضمام عبر الكود": "Join via Code",
    "أدخل كود التحدي هنا...": "Enter challenge code here...",
    "انضمام للتحدي": "Join Challenge",
    "إنشاء رابط التحدي": "Create Challenge Link",
    "تم إنشاء التحدي بنجاح!": "Challenge created successfully!",
    "كود التحدي الخاص بك:": "Your Challenge Code:",
    "نسخ الكود": "Copy Code",
    "تم النسخ!": "Copied!",
    "تفاصيل التحدي": "Challenge Details",
    "تاريخ الإنشاء": "Created at",
    "تاريخ الانتهاء": "Expires at",
    "تاريخ انتهاء التحدي": "Challenge Expiry Date",
    "معاينة الملف": "Preview File",
    "عدد المشاركين": "Participants Count",
    "التحدي الذي انضممت إليه غير موجود": "The challenge you joined does not exist",
    "تحدي الأبطال": "Champions Challenge",
    "المستوى": "Level",
    "الترتيب العالمي": "Global Ranking",
    "خزنة الكؤوس": "Trophy Case",
    "نقاط الخبرة": "Experience Points",
    "ذهبية": "Gold",
    "فضية": "Silver",
    "برونزية": "Bronze",
    "إدارة نظام الجوائز والترتيب": "Manage Rewards and Ranking System",
    "نقاط الفوز (المركز الأول)": "Winner Points (1st Place)",
    "نقاط المستوى التالي": "Points for Next Level",
    "حفظ الإعدادات": "Save Settings",
    "التحديات التي أنشأتها": "My Created Challenges",
    "التحديات التي أنشأتها ولا زالت فعالة": "Challenges you created that are still active",
    "لا توجد تحديات حالية": "No current challenges",
    "تم قبول ملخص «رياضيات الفصل الأول»": "Summary \"Math Chapter 1\" approved",
    "أعجب 5 طلاب بملخص «الخوارزميات»": "5 students liked \"Algorithms\" summary",
    "تم رفض الدورة المضافة لعدم توافقها مع المعايير": "Course rejected for not meeting standards",
    "تم تفعيل اشتراكك بنجاح — مرحبًا بك في VIP": "Subscription activated successfully — Welcome to VIP",
    "منذ ساعتين": "2 hours ago",
    "منذ 4 ساعات": "4 hours ago",
    "أمس": "Yesterday",
    "منذ 3 أيام": "3 days ago",
    "ما هو مبدأ Open/Closed في SOLID؟": "What is the Open/Closed principle in SOLID?",
    "مفتوح للتوسع ومغلق للتعديل": "Open for extension, closed for modification",
    "مفتوح للجميع ومغلق للنظام": "Open to all, closed to the system",
    "مفتوح للتعديل ومغلق للاستخدام": "Open for modification, closed for use",
    "لا شيء مما سبق": "None of the above",
    "أيٌّ مما يلي يُعدّ نمط تصميم Behavioral؟": "Which of the following is a Behavioral design pattern?",
    "ما المقصود بـ Refactoring؟": "What is meant by Refactoring?",
    "ما المقصود بـ Refactoring في هندسة البرمجيات؟": "What is meant by Refactoring in Software Engineering?",
    "إعادة هيكلة الكود بدون تغيير سلوكه": "Restructuring code without changing its behavior",
    "إضافة ميزات جديدة": "Adding new features",
    "إصلاح الأخطاء": "Fixing bugs",
    "حذف الكود القديم": "Deleting old code",
    "استئناف": "Resume",
    "إيقاف": "Pause",
    "السابق →": "Previous →",
    "← التالي": "← Next",
    "← عرض النتائج": "← Show Results",
    " إجابة صحيحة من 20": " correct answers out of 20",
    "وقت الإجابة": "Time taken",
    "الصحيحة": "Correct",
    "الخاطئة": "Incorrect",
    "الدرجة": "Score",
    "← اختبار جديد": "← New Quiz",
    "العودة للوحة التحكم": "Return to Dashboard",
    "مراجعة الأسئلة": "Review Questions",
    "إخفاء": "Hide",
    "عرض المراجعة": "Show Review",
    "س": "Q",
    "إجابتك: ": "Your Answer: ",
    "الإجابة الصحيحة: ": "Correct Answer: ",
    "طالب": "Student",
    "نشط": "Active",
    "متميز": "Distinguished",
    "مستواك الحالي": "Current Level",
    " إعجاب": " Likes",
    "/ 100 نقطة": "/ 100 Points",
    "نقطة واحدة": "One Point",
    "كل 10 إعجابات = نقطة واحدة": "Every 10 likes = 1 point",
    " — يحتاج ": " — Needs ",
    " إعجاب إضافي": " more likes",
    "وصلت للمستوى الأعلى! أنت الآن ": "You reached the highest level! You are now ",

    // Landing Page Additions
    "كيف تعمل المنصة؟": "How does the platform work?",
    "ثلاث خطوات بسيطة تفصلك عن مستقبلك": "Three simple steps away from your future",
    "أنشئ حسابك": "Create your account",
    "سجل في منصة النخبة بخطوات بسيطة وحدد مرحلتك الدراسية الحالية.": "Register on Elite Platform with simple steps and select your current educational stage.",
    "اكتشف تخصصك": "Discover your major",
    "قم بإجراء اختبار الميول الشامل للحصول على تحليل دقيق لشخصيتك وميولك.": "Take the comprehensive aptitude test to get an accurate analysis of your personality and interests.",
    "ابدأ رحلتك": "Start your journey",
    "استفد من الموارد التعليمية، الاختبارات الذكية، ومجتمع طلاب النخبة.": "Benefit from educational resources, smart quizzes, and the Elite students community.",
    "روابط سريعة": "Quick Links",
    "الرئيسية": "Home",
    "عن المنصة": "About Platform",
    "اختبار الميول": "Aptitude Test",
    "المقالات": "Articles",
    "الدعم والمساعدة": "Support & Help",
    "تواصل معنا": "Contact Us",
    "الأسئلة الشائعة": "FAQ",
    "سياسة الخصوصية": "Privacy Policy",
    "شروط الاستخدام": "Terms of Use",
    "منصة النخبة تعليمية متكاملة تهدف إلى مساعدة الطلاب في اختيار تخصصاتهم الجامعية ودعمهم خلال رحلتهم الدراسية.": "Elite Platform is an integrated educational platform aimed at helping students choose their university majors and supporting them throughout their academic journey.",
    "صنعاء، اليمن": "Sana'a, Yemen",
    "© 2024 منصة النخبة. جميع الحقوق محفوظة.": "© 2024 Elite Platform. All rights reserved.",

    // Majors Page
    "الكل": "All",
    "المجال التقني": "Technical Field",
    "علوم الحاسب": "Computer Science",
    "برمجة، خوارزميات، وذكاء اصطناعي. مجال متسارع النمو بفرص عمل واسعة.": "Programming, algorithms, and AI. A rapidly growing field with vast job opportunities.",
    "يركز تخصص علوم الحاسب على دراسة الحوسبة ومعالجة البيانات وتصميم الخوارزميات. يشمل مجالات الذكاء الاصطناعي، وأمن المعلومات، وتطوير الأنظمة المعقدة.": "Computer Science focuses on computing, data processing, and algorithm design. It covers AI, information security, and complex systems development.",
    "مطور برمجيات": "Software Developer",
    "مهندس ذكاء اصطناعي": "AI Engineer",
    "محلل نظم": "Systems Analyst",
    "عالم بيانات": "Data Scientist",
    "هندسة البرمجيات": "Software Engineering",
    "تصميم وبناء الأنظمة البرمجية الضخمة بمنهجيات احترافية.": "Designing and building large-scale software systems using professional methodologies.",
    "تخصص هندسة البرمجيات يعنى بتطبيق مبادئ الهندسة على تطوير البرمجيات، من التخطيط والتصميم إلى فحص الجودة والصيانة المستمرة للأنظمة.": "Software engineering applies engineering principles to software development, from planning and design to QA and continuous maintenance.",
    "مهندس برمجيات": "Software Engineer",
    "مدير مشاريع تقنية": "Technical Project Manager",
    "مختبر جودة": "QA Tester",
    "مهندس معمارية برمجيات": "Software Architect",
    "المجال الطبي": "Medical Field",
    "الطب والجراحة": "Medicine and Surgery",
    "دراسة جسم الإنسان وعلاج الأمراض. من أشرف المهن وأكثرها تأثيرًا.": "Studying the human body and treating diseases. One of the noblest and most impactful professions.",
    "يهدف الطب البشري إلى إعداد أطباء مؤهلين للعناية بصحة الإنسان، وتشخيص وعلاج الأمراض المختلفة باستخدام أحدث الأساليب الطبية والتكنولوجية.": "Human medicine aims to prepare qualified doctors to care for human health, diagnosing and treating diseases using modern medical technologies.",
    "طبيب عام": "General Practitioner",
    "طبيب جراح": "Surgeon",
    "استشاري": "Consultant",
    "باحث طبي": "Medical Researcher",
    "الصيدلة": "Pharmacy",
    "علم الأدوية والمستحضرات الصيدلانية والرعاية الصحية.": "The science of drugs, pharmaceutical products, and healthcare.",
    "تخصص يهتم بابتكار وتطوير وتصنيع الأدوية، بالإضافة إلى تقديم النصائح الطبية للمرضى حول كيفية الاستخدام الآمن والفعال للعلاجات.": "A specialty focused on innovating, developing, and manufacturing drugs, as well as giving medical advice on safe usage.",
    "صيدلي سريري": "Clinical Pharmacist",
    "باحث دوائي": "Pharmaceutical Researcher",
    "مفتش طبي": "Medical Inspector",
    "مدير إنتاج طبي": "Medical Production Manager",
    "المجال الإداري": "Administrative Field",
    "إدارة الأعمال": "Business Administration",
    "التخطيط الاستراتيجي وإدارة المشاريع والقيادة المؤسسية.": "Strategic planning, project management, and corporate leadership.",
    "دراسة شاملة لكيفية عمل المنظمات والشركات، تغطي جوانب الإدارة، التسويق، الموارد البشرية، والمالية لضمان النمو المستدام وتحقيق الأرباح.": "A comprehensive study of organizations and companies, covering management, marketing, HR, and finance for sustainable growth.",
    "مدير تنفيذي": "Executive Director",
    "مستشار أعمال": "Business Consultant",
    "مدير تسويق": "Marketing Manager",
    "رائد أعمال": "Entrepreneur",
    "المجال الإبداعي": "Creative Field",
    "التصميم الجرافيكي": "Graphic Design",
    "التعبير البصري والإبداع الرقمي وتصميم الهوية البصرية.": "Visual expression, digital creativity, and brand identity design.",
    "فن التواصل البصري وحل المشكلات باستخدام الطباعة والتصوير التوضيحي. يهدف إلى إيصال الرسائل بأفضل صورة ممكنة عبر وسائط متعددة.": "The art of visual communication and problem-solving using typography and illustration to convey messages optimally.",
    "مصمم جرافيك": "Graphic Designer",
    "المدير الفني": "Art Director",
    "مصمم واجهات (UI/UX)": "UI/UX Designer",
    "رسام توضيحي": "Illustrator",
    "التخصصات المقترحة": "Suggested Majors",
    "اختر تخصصك المناسب": "Choose Your Ideal Major",
    "بناءً على نتائجك — إليك التخصصات الأكثر توافقًا مع ميولك": "Based on your results — here are the most compatible majors with your interests",
    "اعرف المزيد ←": "Learn More ←",
    "لا توجد تخصصات": "No Majors Found",
    "لم نجد تخصصات مطابقة لهذا المجال حالياً.": "We didn't find any majors matching this field currently.",
    "نبذة عن التخصص": "About the Major",
    "المستقبل الوظيفي المقترح": "Suggested Career Path",
    "اختر هذا التخصص": "Select this Major",
    "إغلاق": "Close",

    // Guards and Auth
    "يلزم تسجيل الدخول": "Login Required",
    "سجّل دخولك أو أنشئ حساباً مجانياً للبدء.": "Log in or create a free account to get started.",
    "العودة للصفحة الرئيسية": "Return to Home Page",
    "← تسجيل الدخول": "← Login",
    "إنشاء حساب مجاني": "Create Free Account",
    "هذا القسم متاح للطلاب المسجلين فقط.": "This section is available to registered students only.",
    "هذا القسم للطلاب الجامعيين فقط": "This section is for University Students only",
    "سجّل حساباً جديداً واختر": "Create a new account and select",
    "لتتمكن من الوصول لجميع ميزات المنصة.": "to access all platform features.",
    "هل أنت طالب جامعي؟": "Are you a university student?",
    "الوصول إلى المواد والاختبارات الأكاديمية متاح حصرياً للطلاب الجامعيين المسجلين.": "Access to academic subjects and quizzes is strictly available to registered university students.",
    "إنشاء حساب طالب جامعي": "Create Student Account",
    "العودة للرئيسية": "Back to Home",

    // About Page
    "عن منصة النخبة": "About Elite Platform",
    "منصة تعليمية عربية متكاملة تُعيد تعريف التجربة الأكاديمية بأدوات الذكاء الاصطناعي": "An integrated Arabic educational platform redefining the academic experience with AI tools",
    "رسالتنا": "Our Mission",
    "نساعد كل طالب يجد طريقه": "Helping every student find their way",
    "تأسست منصة النخبة بهدف واحد واضح: مساعدة الطلاب العرب في اتخاذ قرار التخصص الجامعي بثقة ووعي، ثم دعمهم طوال مسيرتهم الأكاديمية بأحدث أدوات الذكاء الاصطناعي.": "Elite platform was founded with one clear goal: helping Arab students make university major decisions with confidence and awareness, then supporting them throughout their academic journey with latest AI tools.",
    "طالب مسجل": "Registered Student",
    "جامعة مدعومة": "Supported University",
    "مورد دراسي": "Study Resource",
    "رضا المستخدمين": "User Satisfaction",
    "قيمنا الأساسية": "Our Core Values",
    "الدقة والموثوقية": "Accuracy & Reliability",
    "نعتمد على أسس علمية وبيانات موثوقة في كل توصية نقدمها.": "We rely on scientific foundations and reliable data in every recommendation we provide.",
    "المجتمع والتشارك": "Community & Sharing",
    "نؤمن أن التعلم التشاركي يصنع فرقًا حقيقيًا في مسيرة الطالب.": "We believe that collaborative learning makes a real difference in a student's journey.",
    "الابتكار المستمر": "Continuous Innovation",
    "نطوّر أدواتنا باستمرار لمواكبة أحدث تقنيات الذكاء الاصطناعي.": "We constantly develop our tools to keep pace with the latest AI technologies.",

    // Contact Page
    "نحن هنا للمساعدة — تواصل معنا في أي وقت": "We are here to help — contact us anytime",
    "الموقع": "Location",
    "البريد الإلكتروني": "Email",
    "رقم الهاتف": "Phone Number",
    "أوقات العمل": "Working Hours",
    "الأحد – الخميس: 9 صباحًا – 5 مساءً": "Sunday – Thursday: 9 AM – 5 PM",
    "أرسل لنا رسالة": "Send us a message",
    "الاسم الكامل": "Full Name",
    "أدخل اسمك": "Enter your name",
    "أدخل بريدك": "Enter your email",
    "الموضوع": "Subject",
    "موضوع الرسالة": "Message subject",
    "الرسالة": "Message",
    "اكتب رسالتك هنا...": "Write your message here...",
    "← إرسال الرسالة": "Send Message",

    // Admin Dashboard
    "إجمالي المستخدمين": "Total Users",
    "الاشتراكات النشطة": "Active Subscriptions",
    "الموارد المقبولة": "Approved Resources",
    "الاختبارات المولّدة": "Generated Quizzes",
    "هذا الشهر": "this month",
    "نظرة عامة على أداء المنصة": "Overview of platform performance",
    "آخر المستخدمين المسجلين": "Recent Registered Users",
    "الاسم": "Name",
    "البريد": "Email",
    "الدور": "Role",
    "تاريخ التسجيل": "Registration Date",
    "الحالة": "Status",
    "إجراءات": "Actions",
    "اليوم": "Today",
    "أمس": "Yesterday",

    // Admin Users
    "إدارة المستخدمين": "User Management",
    "عرض وإدارة جميع مستخدمي المنصة": "View and manage all platform users",
    "+ إضافة مستخدم": "+ Add User",
    "ابحث عن مستخدم...": "Search for user...",
    "كل الأدوار": "All Roles",
    "تغيير الدور": "Change Role",
    "حظر": "Ban",
    "تنشيط": "Activate",

    // Admin Majors
    "إدارة التخصصات": "Majors Management",
    "إدارة الجامعات والكليات والمجالات والتخصصات والمواد": "Manage universities, faculties, fields, majors and subjects",
    "+ إضافة ": "+ Add ",
    "الجامعة": "University",
    "المدينة": "City",
    "الكليات": "Faculties",
    "التخصصات": "Majors",
    "المواد": "Subjects",
    "المجالات": "Fields",
    "الاسم": "Name",
    "نشطة": "Active",
    "موقوفة": "Suspended",
    "عدد التخصصات": "Majors Count",
    "المجال": "Field",
    "مجاني": "Free",
    "مدفوع": "Paid",
    "تبديل": "Toggle",
    "الكود": "Code",
    "نوع الوصول": "Access Type",
    "تعديل": "Edit",
    "إضافة": "Add",
    "إلغاء": "Cancel",
    "أدخل الاسم...": "Enter name...",
    "← حفظ التعديل": "Save Edit",
    "← إضافة": "Add",
    "تخصصات": "Majors",
    "جامعة صنعاء": "Sana'a University",
    "جامعة عدن": "Aden University",
    "جامعة تعز": "Taiz University",
    "جامعة إب": "Ibb University",
    "صنعاء": "Sana'a",
    "عدن": "Aden",
    "تعز": "Taiz",
    "إب": "Ibb",
    "كلية الهندسة والمعلوماتية": "Faculty of Engineering & IT",
    "كلية الطب والعلوم الصحية": "Faculty of Medicine & Health Sciences",
    "كلية إدارة الأعمال": "Faculty of Business Administration",
    "كلية العلوم": "Faculty of Science",
    "كلية الآداب": "Faculty of Arts",

    // Admin Reports
    "إدارة البلاغات": "Reports Management",
    "مراجعة بلاغات الطلاب واتخاذ الإجراءات اللازمة حيال الموارد المخالفة": "Review student reports and take necessary actions against violating resources",
    "مادة: ": "Subject: ",
    "نوع الملف: ": "File type: ",
    "قيد المراجعة": "Under Review",
    "تم الحذف": "Deleted",
    "تم التجاهل": "Ignored",
    "مقدم البلاغ: ": "Reporter: ",
    "السبب: ": "Reason: ",
    "حذف المورد والإبلاغ ←": "Delete Resource & Report ←",
    "تجاهل البلاغ": "Ignore Report",
    "لا توجد بلاغات حالياً": "No reports currently",

    // Admin Resources
    "إدارة الموارد": "Resources Management",
    "مراجعة وإدارة جميع الموارد المرفوعة": "Review and manage all uploaded resources",
    "الكل": "All",
    "مقبول": "Approved",
    "مرفوض": "Rejected",
    "قبول": "Approve",
    "رفض": "Reject",
    "حذف": "Delete",
    "لا توجد موارد في هذا القسم": "No resources in this section",

    // Admin Subscriptions & Cards
    "إدارة الاشتراكات": "Subscriptions Management",
    "متابعة وإدارة اشتراكات المستخدمين": "Monitor and manage user subscriptions",
    "إنشاء بطاقة اشتراك": "Create Subscription Card",
    "إجمالي الاشتراكات": "Total Subscriptions",
    "إجمالي البطاقات": "Total Cards",
    "غير مستخدمة": "Unused",
    "مستخدمة": "Used",
    "الإيرادات النشطة": "Active Revenue",
    " ر.س": " SAR",
    "الخطة": "Plan",
    "تاريخ البدء": "Start Date",
    "تاريخ الانتهاء": "End Date",
    "المبلغ": "Amount",
    "منتهي": "Expired",
    "بطاقات الاشتراك": "Subscription Cards",
    "إنشاء وإدارة أكواد تفعيل الاشتراكات": "Create and manage subscription activation codes",
    "إنشاء بطاقات جديدة": "Create New Cards",
    "إنشاء بطاقات اشتراك جديدة": "Create New Subscription Cards",
    "نوع الاشتراك": "Subscription Type",
    "عدد البطاقات ": "Number of Cards ",
    "(اكتب أي رقم)": "(Type any number)",
    "ملخص الطلب": "Order Summary",
    " بطاقة": " Cards",
    " جاري التوليد...": " Generating...",
    " توليد ": " Generate ",
    " كود البطاقة": " Card Code",
    "تاريخ الإنشاء": "Creation Date",
    "المستخدم": "User",

    // System Settings
    "التحكم في إعدادات المحتوى والترقية والنقاط": "Control content settings, upgrades, and points",
    "أنواع الملفات المسموحة": "Allowed File Types",
    "الأنواع المسموح للطلاب برفعها": "Types students are allowed to upload",
    "حدود الاختبارات والملفات": "Quizzes and Files Limits",
    "عدد اختبارات الميول المجانية": "Number of Free Interest Tests",
    "اختبار مجاني لكل مستخدم": "Free test per user",
    "الحد الأقصى لحجم الملف": "Max File Size",
    "ميجابايت": "MB",
    "نظام الترقية بالنقاط": "Points-based Upgrade System",
    "نقطة": "Point",
    "عدد عدم الإعجابات لخصم نقطة ": "Number of dislikes to deduct a point ",
    "عند وصول عدم الإعجابات لهذا العدد يُرسَل طلب للمشرف — ": "When dislikes reach this number, a request is sent to the moderator — ",
    "الخصم لا يتم تلقائياً": "Deduction is not automatic",
    "عدم إعجاب": "Dislikes",
    "عدد النقاط المخصومة لإيقاف الطالب ": "Number of deducted points to suspend a student ",
    "حدّد كم نقطة يُسمح بخصمها كحد أقصى": "Specify the maximum points allowed to be deducted",
    "نقطة مخصومة": "Deducted Points",
    "إعدادات النشر والموافقة": "Publishing & Approval Settings",
    "موافقة المشرف مطلوبة": "Moderator Approval Required",
    "كل المواد تمر على مراجعة المشرف قبل النشر": "All materials go through moderator review before publishing",
    "نشر VIP مباشر بدون مراجعة": "Direct VIP Publishing Without Review",
    " الطلاب الذين حصلوا على ": " Students who achieved ",
    " نقطة ينشرون مباشرة": " points publish directly",
    " تم الحفظ": " Saved",
    "← حفظ الإعدادات": "Save Settings",
    "تم تطبيق جميع التغييرات": "All changes applied",

    // Moderator Pages
    "سجل الإجراءات": "Action Log",
    "جميع الإجراءات التي قمت بها على الموارد والبلاغات": "All actions you performed on resources and reports",
    "قبول مورد": "Accept Resource",
    "رفض مورد": "Reject Resource",
    "حذف مورد مُبلَّغ": "Delete Reported Resource",
    "بواسطة ": "By ",
    "الموارد التي أبلغ عنها المستخدمون — تحتاج إلى مراجعة": "Resources reported by users — need review",
    "لا توجد بلاغات معلقة": "No pending reports",
    "كل البلاغات تمت معالجتها": "All reports addressed",
    "المادة": "Subject",
    "صاحب المورد": "Resource Owner",
    "أبلغ عنه بواسطة": "Reported By",
    "تاريخ البلاغ": "Report Date",
    "سبب البلاغ: ": "Report Reason: ",
    " بلاغات": " Reports",
    "حذف المورد": "Delete Resource",
    "خصم نقطة وحذف": "Deduct Point & Delete",
    "مراجعة وإدارة جميع الموارد المرفوعة من الطلاب": "Review and manage all resources uploaded by students",
    "إعادة قبول": "Re-approve",
    "رفض": "Reject",
    "العودة للرئيسية": "Back to Home",

    // Admin Suggestions
    "إدارة الاقتراحات": "Suggestions Management",
    "استعراض مقترحات الطلاب لتطوير المنصة": "Review student suggestions for platform development",
    "اقتراح جديد": "New Suggestion",
    "تمت المراجعة": "Reviewed",
    "الطالب: ": "Student: ",
    "تحديد كمقروء ": "Mark as read ",
    "حذف": "Delete",
    "لا توجد اقتراحات حالياً": "No suggestions currently",
    "إضافة فيديوهات شرح لكل مادة": "Add explanation videos for each subject",
    "أقترح بناء مكتبة فيديوهات قصيرة تشرح أهم المواضيع، سيسهل علينا الفهم جداً وتقليل وقت المذاكرة.": "I suggest building a small video library explaining core topics, it would really help us understand better and reduce study time.",
    "تحديات أسبوعية على مستوى الجامعة": "Weekly university-wide challenges",
    "ياليت يكون فيه نظام تحديات بين الكليات يجمع نقاط ويرتب الكليات حسب النشاط لخلق جو تنافسي.": "It would be great if there was a challenge system between colleges to collect points and rank them based on activity to create a competitive atmosphere.",
    "إظهار تقييم الدكاترة للمواد": "Show doctor ratings for subjects",
    "أتمنى إضافة ميزة لتقييم الدكاترة من قبل الطلاب لتسهيل اختيار الشعب في النظام الجامعي الأساسي.": "I hope to add a feature for students to rate doctors to facilitate choosing sections in the main university system.",
    "فهد أحمد": "Fahd Ahmed",

    // Sample Data Translations (Moderator & Admin)
    "ملخص قواعد البيانات — الفصل الثاني": "Database Summary — Chapter 2",
    "محمد المشرف": "Mohammed Moderator",
    "اليوم، 10:45 ص": "Today, 10:45 AM",
    "ملخص غير مكتمل — نظم التشغيل": "Incomplete Summary — OS",
    "أمس، 3:22 م": "Yesterday, 3:22 PM",
    "حذف مورد مُبلَّغ": "Delete Reported Resource",
    "تجاهل بلاغ": "Ignore Report",
    "محتوى مسروق — خوارزميات": "Stolen Content — Algorithms",
    "أمس، 1:10 م": "Yesterday, 1:10 PM",
    "دورة Python للمبتدئين": "Python for Beginners",
    "12 مارس، 4:00 م": "March 12, 4:00 PM",
    "مقارنة بين Agile و Waterfall": "Agile vs Waterfall Comparison",
    "10 مارس، 11:30 ص": "March 10, 11:30 AM",
    "ملخص مسروق — هندسة البرمجيات": "Stolen Summary — Software Engineering",
    "فاطمة حسن": "Fatima Hassan",
    "محمد العلي": "Mohammed Al-Ali",
    "محتوى منقول بدون إذن": "Content copied without permission",
    "اليوم، 11:20 ص": "Today, 11:20 AM",
    "دورة خارجية — Python للمبتدئين": "External Course — Python for Beginners",
    "أحمد السالم": "Ahmed Al-Salem",
    "خالد السعد": "Khaled Al-Saad",
    "الرابط لا يعمل": "Link not working",
    "أمس، 4:10 م": "Yesterday, 4:10 PM",
    "ملخص قواعد البيانات — فصل 2": "Database Summary — Chapter 2",
    "سارة محمد": "Sarah Mohammed",
    "نورة خالد": "Noura Khaled",
    "محتوى غير مناسب": "Inappropriate Content",
    "12 مارس": "March 12",
    "تم حذف المورد المُبلَّغ عنه": "Reported resource deleted",
    "تم تجاهل البلاغ": "Report ignored",
    "ملخص الفصل الأول — UML و Design Patterns": "Chapter 1 Summary — UML & Design Patterns",
    "التخصصات": "Majors",
    "الملف الجامعي": "University Profile",
    "بيانات الطالب الجامعي": "University Student Data",
    "أكمل هذه البيانات لتفعيل ميزات المواد الأكاديمية والاختبارات": "Complete this data to activate academic materials and tests",
    "تحديث بيانات الجامعة": "Update University Data",
    "تفعيل حساب الطالب الجامعي": "Activate University Student Profile",
    "مستخدم مهتم": "Interested User",
    "أهلاً بك في منصة النخبة!": "Welcome to Elite Platform!",
    "أنت الآن تستخدم الحساب المحدود. للحصول على كامل المزايا الأكاديمية مثل المواد، الاختبارات، والموارد، يرجى إكمال بياناتك كطالب جامعي.": "You are currently using the limited account. To get full academic benefits such as materials, tests, and resources, please complete your data as a university student.",
    "إكمال ملف الطالب الجامعي": "Complete University Student Profile",
    "استكشاف التخصصات": "Explore Majors",
    "هل أنت محتار في اختيار تخصصك؟": "Are you confused about choosing your major?",
    "قم بإجراء اختبار تحديد الميول المهنية لنساعدك في اختيار المسار الأنسب لشخصيتك.": "Take the career interest test to help you choose the best path for your personality.",
    "ابدأ اختبار الميول الآن": "Start Interest Test Now",
    "أكمل بياناتك الجامعية في الإعدادات أو ": "Complete your university data in settings or ",
    "اضغط هنا": "Click here",
    "ملاحظات محاضرة 3 — Software Testing": "Lecture 3 Notes — Software Testing",
    "دورة Python للمبتدئين - YouTube": "Python for Beginners - YouTube",
    "مراجعة شاملة قبل الاختبار النهائي": "Comprehensive Review Before Final",
    "شرح مفصل للـ Design Patterns": "Detailed Design Patterns Explanation",
    "عمر جواد": "Omar Jawad",
    "ريم عبدالله": "Reem Abdullah",
    "✅ تم قبول المورد بنجاح": "✅ Resource approved successfully",
    "❌ تم رفض المورد": "❌ Resource rejected",
    "🗑️ تم حذف المورد نهائياً": "🗑️ Resource permanently deleted",
    "قام بإضافة": "Added",
    "قام بتعديل": "Updated",
    "قام بحذف": "Deleted",
    "قام باعتماد": "Approved",
    "ألغى اعتماد": "Unapproved",
    "سجل دخوله": "Logged in",
    "سجل خروجه": "Logged out",
    "حاول الدخول وفشل": "Failed login attempt",
  }
};

export const LanguageContext = createContext({
  lang: 'ar',
  toggleLang: () => { },
  t: (text) => text,
  dir: 'rtl'
});

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('ar');

  const toggleLang = () => {
    setLang(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (text) => {
    if (lang === 'ar') return text; // Base language
    return dictionaries['en'][text] || text; // Fallback to original text if missing
  };

  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', lang);
  }, [lang, dir]);

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
